# Alap image .NET-hez (SDK a fejlesztéshez/build-hez)
FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

# Amíg nincs tényleges kód, ez egy minimális előkészítés, 
# ami ébren tartja a konténert
CMD ["tail", "-f", "/dev/null"]
